<?xml version="1.0" encoding="utf-8"?><Database Name="db_gnwble" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=db_gnwble;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="db_gnwbleConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.course" Member="courses">
    <Type Name="course">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="trainer_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="course_type_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="course_assigned_course" Member="assigned_courses" ThisKey="id" OtherKey="course_id" Type="assigned_course" />
      <Association Name="course_test" Member="tests" ThisKey="id" OtherKey="course_id" Type="test" />
      <Association Name="course_lesson" Member="lessons" ThisKey="id" OtherKey="course_id" Type="lesson" />
      <Association Name="course_type_course" Member="course_type" ThisKey="course_type_id" OtherKey="id" Type="course_type" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.department" Member="departments">
    <Type Name="department">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="company_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="department_staff" Member="staffs" ThisKey="id" OtherKey="department_id" Type="staff" />
      <Association Name="company_department" Member="company" ThisKey="company_id" OtherKey="id" Type="company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.region" Member="regions">
    <Type Name="region">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="region_company" Member="companies" ThisKey="id" OtherKey="region_id" Type="company" />
    </Type>
  </Table>
  <Table Name="dbo.role" Member="roles">
    <Type Name="role">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="role_staff" Member="staffs" ThisKey="id" OtherKey="role_id" Type="staff" />
    </Type>
  </Table>
  <Table Name="dbo.company" Member="companies">
    <Type Name="company">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="region_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="company_department" Member="departments" ThisKey="id" OtherKey="company_id" Type="department" />
      <Association Name="region_company" Member="region" ThisKey="region_id" OtherKey="id" Type="region" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.assigned_course" Member="assigned_courses">
    <Type Name="assigned_course">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="start_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="end_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="course_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="assigned_course_staff_assigned_course" Member="staff_assigned_courses" ThisKey="id" OtherKey="assigned_course_id" Type="staff_assigned_course" />
      <Association Name="course_assigned_course" Member="course" ThisKey="course_id" OtherKey="id" Type="course" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.test" Member="tests">
    <Type Name="test">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="course_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="answers" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="test_test_result" Member="test_results" ThisKey="id" OtherKey="test_id" Type="test_result" />
      <Association Name="course_test" Member="course" ThisKey="course_id" OtherKey="id" Type="course" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.test_result" Member="test_results">
    <Type Name="test_result">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="staff_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="test_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="start_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="end_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="result" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="answers" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="test_test_result" Member="test" ThisKey="test_id" OtherKey="id" Type="test" IsForeignKey="true" />
      <Association Name="staff_test_result" Member="staff" ThisKey="staff_id" OtherKey="id" Type="staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.course_type" Member="course_types">
    <Type Name="course_type">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="course_type_course" Member="courses" ThisKey="id" OtherKey="course_type_id" Type="course" />
    </Type>
  </Table>
  <Table Name="dbo.completion_status" Member="completion_status">
    <Type Name="completion_status">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="completion_status_staff_assigned_course" Member="staff_assigned_courses" ThisKey="id" OtherKey="completion_status_id" Type="staff_assigned_course" />
    </Type>
  </Table>
  <Table Name="dbo.lesson" Member="lessons">
    <Type Name="lesson">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="course_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="duration_in_minutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="course_lesson" Member="course" ThisKey="course_id" OtherKey="id" Type="course" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.staff_assigned_course" Member="staff_assigned_courses">
    <Type Name="staff_assigned_course">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="staff_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="assigned_course_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="percent_completed" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="completion_status_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="assigned_course_staff_assigned_course" Member="assigned_course" ThisKey="assigned_course_id" OtherKey="id" Type="assigned_course" IsForeignKey="true" />
      <Association Name="completion_status_staff_assigned_course" Member="completion_status" ThisKey="completion_status_id" OtherKey="id" Type="completion_status" IsForeignKey="true" />
      <Association Name="staff_staff_assigned_course" Member="staff" ThisKey="staff_id" OtherKey="id" Type="staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.fd_ua_nums" Member="fd_ua_nums">
    <Type Name="fd_ua_num">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ua" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.staff" Member="staffs">
    <Type Name="staff">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="role_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="department_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email_address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="staff_staff_assigned_course" Member="staff_assigned_courses" ThisKey="id" OtherKey="staff_id" Type="staff_assigned_course" />
      <Association Name="staff_test_result" Member="test_results" ThisKey="id" OtherKey="staff_id" Type="test_result" />
      <Association Name="role_staff" Member="role" ThisKey="role_id" OtherKey="id" Type="role" IsForeignKey="true" />
      <Association Name="department_staff" Member="department" ThisKey="department_id" OtherKey="id" Type="department" IsForeignKey="true" />
    </Type>
  </Table>
</Database>